apiVersion: apps/v1
kind: Deployment
metadata:
  name: $CI_PROJECT_NAME
spec:
  selector:
    matchLabels:
      app: $CI_PROJECT_NAME
  template:
    metadata:
      labels:
        app: $CI_PROJECT_NAME
        component: backend
    spec:
      containers:
        - name: $CI_PROJECT_NAME-bot
          image: paritytech/$DOCKER_IMAGE-bot:$DOCKER_TAG
          env:
            - name: MATRIX_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: $CI_PROJECT_NAME-config
                  key: matrix-access-token
            - name: BACKEND_URL
              value: "http://localhost:5555"
          imagePullPolicy: Always
          resources:
            requests:
               cpu: 10m
               memory: 100Mi
            limits:
               cpu: 100m
               memory: 256Mi
        - name: $CI_PROJECT_NAME-server
          image: paritytech/$DOCKER_IMAGE-server:$DOCKER_TAG
          env:
            - name: MNEMONIC
              valueFrom:
                secretKeyRef:
                  name: $CI_PROJECT_NAME-config
                  key: mnemonic
          livenessProbe:
            httpGet:
              path: /health
              port: 5555
            failureThreshold: 1
            periodSeconds: 30
            initialDelaySeconds: 15
          imagePullPolicy: Always
          resources:
            requests:
               cpu: 10m
               memory: 100Mi
            limits:
               cpu: 100m
               memory: 256Mi
